site_name: MetalMercs Corepedia

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: amber


extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Factions:
      - Helios Sovereignty: factions/helios-sovereignty.md
  - Society:
      - Mercenaries: society/mercenaries.md